Resolve #67
plume-sig/zk-nullifier-sig pull request #93
Opened 2024-02-13 12:58 UTC by skaunov

`arkworks-rs` have some issue while publishing (to <crates.io>) concerned with `serde` dependency. I don't feel like delving into that one is reasonable giving that it's outdated anyway. It's API have been sorted out, and documented.

The other crate can be found at <https://crates.io/crates/plume_rustcrypto>. Any changes to it are welcome: let's add it to this PR. 

Then squash and merge.

2024-02-14 15:39 UTC, Divide-By-0 requested changes
Mostly on crate rename.

2024-02-14 15:39 UTC, Divide-By-0 commented on rust-arkworks/src/lib.rs
> +/// Find RustCrypto crate as `plume_crypto`.
This one can be plume_arkworks

2024-02-14 15:39 UTC, Divide-By-0 commented on rust-k256/Cargo.toml
> +name = "plume_rustcrypto"
Let's make this one plume_crypto, and the other one plume_arkworks!

2024-02-14 15:39 UTC, Divide-By-0 commented on rust-k256/src/lib.rs
> +//! Find `arkworks-rs` crate as `plume_arkworks`.
Ah you already did this in some places!

2024-02-14 15:50 UTC, skaunov commented
@Divide-By-0 ,
that `plume_rustcrypto` naming was actually last minute change, since I too wanted to go with "plume_crypto" for some time. But going through all the thing and some crates I felt like it's not communicating that clear that there's two versions: for `arkworks-rs` and for RustCrypto ecosystems. So made it a bit more specific. Let's give some time to make its way to how they both look... And it can be transferred easily to that other name. :shrug:

2024-02-14 17:45 UTC, Divide-By-0 commented
> RustCrypto

That makes sense then, as long as the naming is consistent i.e. fix the 'Find RustCrypto crate as `plume_crypto`.' comment!

2024-02-15 00:32 UTC, skaunov commented
All are very valid points, I just need to come to something on how to best express them. :sweat_smile: I mean some doesn't go that smooth when trying.

1) I don't like this *bare* look too. Though all I came up with is the link to this repo <README.MD> file; since that page isn't documentation yet, but it contains the link to the documentation (the one which `cargo doc` / `pub` interfaces) in the designated section. When it's not a monorepo stuff we have in the actual <README.MD> goes there. Hence the link. I don't like copying it, since it's kinda awkward to bump version with just <README.MD> changes... Any better ideas are welcome!

2) That one is confusing, since there's a couple of quick ways to get to <https://docs.rs/plume_rustcrypto/> really fast, and the link from the crate page is one of them. So people are really don't expect that.

3) This one is really needed. I thought that the API is really small for adding an example, but they're always good! The problem is that without `sign` method it's hard to show the thing concisely; so I guess I'll do that one before closing this. Also I'll add the example to the other crate just so it would be present and maintained, and came naturally when that crate will be there.

For the last one I added a HAZMAT notice.

2024-02-15 20:15 UTC, Divide-By-0 commented
> All are very valid points, I just need to come to something on how to best express them. 😅 I mean some doesn't go that smooth when trying.
> 
> 1. I don't like this _bare_ look too. Though all I came up with is the link to this repo <README.MD> file; since that page isn't documentation yet, but it contains the link to the documentation (the one which `cargo doc` / `pub` interfaces) in the designated section. When it's not a monorepo stuff we have in the actual <README.MD> goes there. Hence the link. I don't like copying it, since it's kinda awkward to bump version with just <README.MD> changes... Any better ideas are welcome!
> 2. That one is confusing, since there's a couple of quick ways to get to https://docs.rs/plume_rustcrypto/ really fast, and the link from the crate page is one of them. So people are really don't expect that.
> 3. This one is really needed. I thought that the API is really small for adding an example, but they're always good! The problem is that without `sign` method it's hard to show the thing concisely; so I guess I'll do that one before closing this. Also I'll add the example to the other crate just so it would be present and maintained, and came naturally when that crate will be there.
> 
> For the last one I added a HAZMAT notice.

1. Sweet. It's totally fine to bump version with a README change -- no one's using it yet haha.
2. Yeah, we should just include that docs.rs link in the README and in the github repo.
3. Makes sense, lets do it in that order then.

2024-02-15 20:17 UTC, Divide-By-0 approved these changes

2024-02-15 20:18 UTC, merged

2024-02-15 20:19 UTC, Divide-By-0 commented
Going to merge this for now so that the README shows up in the crates docs -- i expect this issue is still open however till we get sign merged etc!

2024-02-15 22:52 UTC, skaunov commented
Two tiny notes. I meant not the version counter but the fact that it 
would be always behind actual <README.MD> without any reason for it. 
And basically the link is always on the page where people used to find 
it; no problem to double it, but it would be helpful only for that rare 
occasion when someone would receive the crate outside <crates.io> and 
Github. %)
On Thu, Feb 15 2024 at 12:16:10 PM -0800, Yush G 
***@***.***> wrote:
>> I don't like this /bare/ look too. Though all I came up with is the 
>> link to this repo <README.MD> file; since that page isn't 
>> documentation yet, but it contains the link to the documentation 
>> (the one which cargo doc / pub interfaces) in the designated 
>> section. When it's not a monorepo stuff we have in the actual 
>> <README.MD> goes there. Hence the link. I don't like copying it, 
>> since it's kinda awkward to bump version with just <README.MD> 
>> changes... Any better ideas are welcome!
> Sweet. It's totally fine to bump version with a README change -- no 
> one's using it yet haha. Yeah, we should just include that docs.rs 
> link in the README and in the github repo.
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/plume-sig/zk-nullifier-sig/pull/93#issuecomment-1947241277>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/APXLOT4AS3BBQ3PHWQEJJZLYTZUIVAVCNFSM6AAAAABDGO4GU6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBXGI2DCMRXG4>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>